# StepCommand Configuration File
# Version 1.0.1

# Numeric ID of the block
block-id: 1
# Command executor [console / player]
executor: "console"
# Command that is executed
command: "warp somewherenice"

# MutliWorld support [true / false]
multiworld-enabled: false
# World where the execution is enabled
world: "world"
