# StepCommand Configuration File
# Version 1.0.5

# Use {player} for player name and {world} for world the player is in

# Numeric ID of the block
blocks: 
  - 1
  - 2
# Command executor [console / player]
executor: "console"
# Commands that is executed, use {player} for player name and {world} for world the player is in.
commands: 
  - msg {player} Hello! This is StepCommand. Please set up this plugin in the configuration file located in plugin_data/StepCommand or plugins/StepCommand

# MutliWorld support [true / false]
multiworld-enabled: false

# Worlds where the execution is enabled, make sure the list is in the following format
  # enabled-worlds:
  # - "example1"
  # - "example 2"

enabled-worlds:
  - world
  - example 2