# StepCommand Configuration File
# Version 1.0.2

# Use {player} for player name and {world} for world the player is in

# Numeric ID of the block
block-id: 1
# Command executor [console / player] use {player} for player name and {world} for world the player is in.
executor: "console"
# Command that is executed, use {player} for player name and {world} for world the player is in.
command: "say {player} is nice"

# MutliWorld support [true / false]
multiworld-enabled: false
# World where the execution is enabled
world: "world"
